export const countries_ru = [
    { value: 27, rel: 0, name: 'Албания' },
    { value: 36, rel: 0, name: 'Аргентина' },
    { value: 10, rel: 0, name: 'Германия' },
    { value: 29, rel: 0, name: 'Соединённые Штаты Америки' },
    { value: 30, rel: 0, name: 'Американское Самоа' },
    { value: 31, rel: 0, name: 'Андорра' },
    { value: 34, rel: 0, name: 'Антарктида' },
    { value: 35, rel: 0, name: 'Антигуа и Барбуда' },
    { value: 11, rel: 1, name: 'Беларусь' },
    { value: 12, rel: 1, name: 'Республика Молдовы' },
    { value: 13, rel: 1, name: 'Грузия' },
    { value: 14, rel: 1, name: 'Казахстан' },
    { value: 15, rel: 1, name: 'Кыргызстан' },
    { value: 16, rel: 1, name: 'Россия' },
    { value: 17, rel: 1, name: 'Таджикистан' },
    { value: 19, rel: 1, name: 'Украниа' },
    { value: 24, rel: 0, name: 'Алжир' },
    { value: 33, rel: 0, name: 'Агола' },
    { value: 37, rel: 0, name: 'Аруба' },
    { value: 38, rel: 0, name: 'Австралия' },
    { value: 39, rel: 0, name: 'Австрия' },
    { value: 40, rel: 0, name: 'Азербайджан' },
    { value: 41, rel: 0, name: 'Багамские Острова' },
    { value: 42, rel: 0, name: 'Бангладеш' },
    { value: 43, rel: 0, name: 'Барбадос' },
    { value: 44, rel: 0, name: 'Бельгия' },
    { value: 45, rel: 0, name: 'Белиз' },
    { value: 46, rel: 0, name: 'Бенин' },
    { value: 47, rel: 0, name: 'Бермуды' },
    { value: 48, rel: 0, name: 'Бахрейн' },
    { value: 49, rel: 0, name: 'Объедененные Арабские Эмираты' },
    { value: 50, rel: 0, name: 'Танзания' },
    { value: 51, rel: 0, name: 'Боливия' },
    { value: 52, rel: 0, name: 'Болгария' },
    { value: 53, rel: 0, name: 'Бонайре, Синт-Эстатиус и Саба' },
    { value: 54, rel: 0, name: 'Босния и Герцеговина' },
    { value: 55, rel: 0, name: 'Ботсвана' },
    { value: 56, rel: 0, name: 'Великобритания' },
    { value: 57, rel: 0, name: 'Бразилия' },
    { value: 58, rel: 0, name: 'Бруней' },
    { value: 59, rel: 0, name: 'Буркина-Фасо' },
    { value: 60, rel: 0, name: 'Бурунди' },
    { value: 61, rel: 0, name: 'Бутан' },
    { value: 64, rel: 0, name: 'Гибралтар' },
    { value: 65, rel: 0, name: 'Южно-Африканская Республика' },
    { value: 66, rel: 0, name: 'Южный Судан' },
    { value: 67, rel: 0, name: 'Джибути' },
    { value: 69, rel: 0, name: 'Чад' },
    { value: 70, rel: 0, name: 'Чехия' },
    { value: 71, rel: 0, name: 'Чили' },
    { value: 72, rel: 0, name: 'Китай' },
    { value: 73, rel: 0, name: 'Данимарка' },
    { value: 74, rel: 0, name: 'Доминика' },
    { value: 75, rel: 0, name: 'Доминиканская Республика' },
    { value: 76, rel: 0, name: 'Эквадор' },
    { value: 77, rel: 0, name: 'Экваториальная Гвинея' },
    { value: 78, rel: 0, name: 'Эритрея' },
    { value: 81, rel: 0, name: 'Эстония' },
    { value: 82, rel: 0, name: 'Фарерские острова' },
    { value: 83, rel: 0, name: 'Фиджи' },
    { value: 84, rel: 0, name: 'Филиппины' },
    { value: 85, rel: 0, name: 'Финляндия' },
    { value: 87, rel: 0, name: 'Франция' },
    { value: 92, rel: 0, name: 'Гаити' },
    { value: 97, rel: 0, name: 'Индия' },
    { value: 98, rel: 0, name: 'Гондурас' },
    { value: 100, rel: 0, name: 'Индонезия' },
    { value: 101, rel: 0, name: 'Иордания' },
    { value: 102, rel: 0, name: 'Ирак' },
    { value: 103, rel: 0, name: 'Иран' },
    { value: 104, rel: 0, name: 'Ирландия' },
    { value: 105, rel: 0, name: 'Исландия' },
    { value: 106, rel: 0, name: 'Испания' },
    { value: 107, rel: 0, name: 'Израиль' },
    { value: 108, rel: 0, name: 'Швеция' },
    { value: 109, rel: 0, name: 'Швейцария' },
    { value: 111, rel: 0, name: 'Италия' },
    { value: 113, rel: 0, name: 'Камбоджа' },
    { value: 114, rel: 0, name: 'Камерун' },
    { value: 115, rel: 0, name: 'Канада' },
    { value: 117, rel: 0, name: 'Кения' },
    { value: 119, rel: 0, name: 'Кипр' },
    { value: 121, rel: 0, name: 'Колумбия' },
    { value: 122, rel: 0, name: 'Республика Конг' },
    { value: 123, rel: 0, name: 'Корея (КНДР)' },
    { value: 124, rel: 0, name: 'Республика Корея' },
    { value: 125, rel: 0, name: 'Коста-Рика' },
    { value: 126, rel: 0, name: 'Кот-д’Ивуар' },
    { value: 127, rel: 0, name: 'Куба' },
    { value: 130, rel: 0, name: 'Кувейт' },
    { value: 131, rel: 0, name: 'Лаос' },
    { value: 132, rel: 0, name: 'Латвия' },
    { value: 133, rel: 0, name: 'Лесото' },
    { value: 134, rel: 0, name: 'Либерия' },
    { value: 135, rel: 0, name: 'Литва' },
    { value: 136, rel: 0, name: 'Ливан' },
    { value: 137, rel: 0, name: 'Ливия' },
    { value: 138, rel: 0, name: 'Лихтенштейн' },
    { value: 139, rel: 0, name: 'Люксембург' },
    { value: 140, rel: 0, name: 'Венгрия' },
    { value: 141, rel: 0, name: 'Мадагаскар' },
    { value: 143, rel: 0, name: 'Македония' },
    { value: 144, rel: 0, name: 'Малави' },
    { value: 145, rel: 0, name: 'Малайзия' },
    { value: 146, rel: 0, name: 'Мальдивы' },
    { value: 147, rel: 0, name: 'Мали' },
    { value: 148, rel: 0, name: 'Мальта' },
    { value: 149, rel: 0, name: 'Маршалловы Остров' },
    { value: 151, rel: 0, name: 'Маврикий' },
    { value: 152, rel: 0, name: 'Мавритания' },
    { value: 153, rel: 0, name: 'Мексика' },
    { value: 156, rel: 0, name: 'Марокко' },
    { value: 157, rel: 0, name: 'Центрально-Африканская Республика' },
    { value: 158, rel: 0, name: 'Федеративные Штаты Микронезии' },
    { value: 160, rel: 0, name: 'Египет' },
    { value: 162, rel: 0, name: 'Монголия' },
    { value: 163, rel: 0, name: 'Черногория' },
    { value: 165, rel: 0, name: 'Мозамбик' },
    { value: 166, rel: 0, name: 'Остров Святой Елены' },
    { value: 167, rel: 0, name: 'Мьянма' },
    { value: 168, rel: 0, name: 'Намибия' },
    { value: 169, rel: 0, name: 'Науру' },
    { value: 170, rel: 0, name: 'Непал' },
    { value: 171, rel: 0, name: 'Нидерланды' },
    { value: 173, rel: 0, name: 'Нигер' },
    { value: 174, rel: 0, name: 'Нигерия' },
    { value: 175, rel: 0, name: 'Никарагуа' },
    { value: 178, rel: 0, name: 'Норвегия' },
    { value: 179, rel: 0, name: 'Оман' },
    { value: 180, rel: 0, name: 'Кабон' },
    { value: 181, rel: 0, name: 'Гамбия' },
    { value: 182, rel: 0, name: 'Кана' },
    { value: 183, rel: 0, name: 'Каяна' },
    { value: 184, rel: 0, name: 'Катар' },
    { value: 186, rel: 0, name: 'Гренада' },
    { value: 190, rel: 0, name: 'Гватемала' },
    { value: 191, rel: 0, name: 'Гвинея' },
    { value: 193, rel: 0, name: 'Узбекистан' },
    { value: 194, rel: 0, name: 'Пакистан' },
    { value: 195, rel: 0, name: 'Палау' },
    { value: 197, rel: 0, name: 'Панама' },
    { value: 198, rel: 0, name: 'Папуа — Новая Гвинея' },
    { value: 199, rel: 0, name: 'Парагвай' },
    { value: 200, rel: 0, name: 'Перу' },
    { value: 203, rel: 0, name: 'Польша' },
    { value: 204, rel: 0, name: 'Португалия' },
    { value: 205, rel: 0, name: 'Пуэрто-Рико (США)' },
    { value: 209, rel: 0, name: 'Руанда' },
    { value: 210, rel: 0, name: 'Румыния' },
    { value: 212, rel: 0, name: 'Самоа' },
    { value: 213, rel: 0, name: 'Сан-Марино' },
    { value: 215, rel: 0, name: 'Сенегал' },
    { value: 222, rel: 0, name: 'Сербия' },
    { value: 223, rel: 0, name: 'Сейшельские острова' },
    { value: 224, rel: 0, name: 'Саудовская Аравия' },
    { value: 225, rel: 0, name: 'Сингапур' },
    { value: 227, rel: 0, name: 'Словакия' },
    { value: 228, rel: 0, name: 'Словения' },
    { value: 230, rel: 0, name: 'Сомали' },
    { value: 231, rel: 0, name: 'Судан' },
    { value: 233, rel: 0, name: 'Суринам' },
    { value: 234, rel: 0, name: 'Сирия' },
    { value: 235, rel: 0, name: 'Эсватини' },
    { value: 236, rel: 0, name: 'Леоне' },
    { value: 239, rel: 0, name: 'Шри-Ланка' },
    { value: 240, rel: 0, name: 'Таиланд' },
    { value: 241, rel: 0, name: 'Тайвань' },
    { value: 244, rel: 0, name: 'Тонга' },
    { value: 245, rel: 0, name: 'Того' },
    { value: 246, rel: 0, name: 'Тринидад и Тобаго' },
    { value: 247, rel: 0, name: 'Тунис' },
    { value: 249, rel: 0, name: 'Тувалу' },
    { value: 250, rel: 0, name: 'Турция' },
    { value: 251, rel: 0, name: 'Туркмения' },
    { value: 252, rel: 0, name: 'Uqanda' },
    { value: 253, rel: 0, name: 'Уганда' },
    { value: 254, rel: 0, name: 'Вануату' },
    { value: 255, rel: 0, name: 'Ватикан' },
    { value: 256, rel: 0, name: 'Венесуэла' },
    { value: 260, rel: 0, name: 'Вьетнам' },
    { value: 261, rel: 0, name: 'Хорватия' },
    { value: 262, rel: 0, name: 'Ямайка' },
    { value: 263, rel: 0, name: 'Япония' },
    { value: 265, rel: 0, name: 'Новая Зеландия' },
    { value: 266, rel: 0, name: 'Йемен' },
    { value: 7, rel: 0, name: 'Греция' },
    { value: 4, rel: 0, name: 'Зимбабве' },
    { value: 5, rel: 0, name: 'Замбия' },
  ]
  