export const countries_az = [
    { value:27, rel:0, name: "Albaniya" },
    { value:36, rel:0, name: "Argentina" },
    { value:10, rel:0, name: "Almaniya" },
    { value:29, rel:0, name: "Amerika Birləşmiş Ştatları" },
    { value:30, rel:0, name: "Amerika Samoası" },
    { value:31, rel:0, name: "Andorra" },
    { value:34, rel:0, name: "Antarktika" },
    { value:35, rel:0, name: "Antiqua və Barbuda" },
    { value:11, rel:1, name: "Belarus" },
    { value:12, rel:1, name: "Moldova Respublikası" },
    { value:13, rel:1, name: "Gürcüstan" },
    { value:14, rel:1, name: "Qazaxıstan" },
    { value:15, rel:1, name: "Qırğızıstan" },
    { value:16, rel:1, name: "Rusiya Federasiyası" },
    { value:17, rel:1, name: "Tacikistan" },
    { value:19, rel:1, name: "Ukrayna" },
    { value:24, rel:0, name: "Əlcəzair" },
    { value:33, rel:0, name: "Anqola" },
    { value:37, rel:0, name: "Aruba" },
    { value:38, rel:0, name: "Avstraliya" },
    { value:39, rel:0, name: "Avstriya" },
    { value:40, rel:0, name: "Azərbaycan" },
    { value:41, rel:0, name: "Baham adaları" },
    { value:42, rel:0, name: "Banqladeş" },
    { value:43, rel:0, name: "Barbados" },
    { value:44, rel:0, name: "Belçika" },
    { value:45, rel:0, name: "Beliz" },
    { value:46, rel:0, name: "Benin" },
    { value:47, rel:0, name: "Bermud adaları" },
    { value:48, rel:0, name: "Bəhreyn" },
    { value:49, rel:0, name: "Birləşmiş Ərəb Əmirlikləri" },
    { value:50, rel:0, name: "Birləşmiş Tanzaniya Respublikası" },
    { value:51, rel:0, name: "Boliviya" },
    { value:52, rel:0, name: "Bolqarıstan" },
    { value:53, rel:0, name: "Boneyr, Sent-Estatius və Saba" },
    { value:54, rel:0, name: "Bosniya və Herseqovina" },
    { value:55, rel:0, name: "Botsvana" },
    { value:56, rel:0, name: "Böyük Britaniya" },
    { value:57, rel:0, name: "Braziliya" },
    { value:58, rel:0, name: "Bruney-Darüssalam" },
    { value:59, rel:0, name: "Burkina-Faso" },
    { value:60, rel:0, name: "Burundi" },
    { value:61, rel:0, name: "Butan" },
    { value:64, rel:0, name: "Cəbəllütariq" },
    { value:65, rel:0, name: "Cənubi Afrika Respublikası" },
    { value:66, rel:0, name: "Cənubi Sudan" },
    { value:67, rel:0, name: "Cibuti" },
    { value:69, rel:0, name: "Çad" },
    { value:70, rel:0, name: "Çexiya Respublikası" },
    { value:71, rel:0, name: "Çili" },
    { value:72, rel:0, name: "Çin" },
    { value:73, rel:0, name: "Danimarka" },
    { value:74, rel:0, name: "Dominika" },
    { value:75, rel:0, name: "Dominikan Respublikası" },
    { value:76, rel:0, name: "Ekvador" },
    { value:77, rel:0, name: "Ekvatorial Qvineya" },
    { value:78, rel:0, name: "Eritreya" },
    { value:81, rel:0, name: "Estoniya" },
    { value:82, rel:0, name: "Farer adaları" },
    { value:83, rel:0, name: "Fici" },
    { value:84, rel:0, name: "Filippin" },
    { value:85, rel:0, name: "Finlandiya" },
    { value:87, rel:0, name: "Fransa" },
    { value:92, rel:0, name: "Haiti" },
    { value:97, rel:0, name: "Hindistan" },
    { value:98, rel:0, name: "Honduras" },
    { value: 100, rel:0, name: "İndoneziya" },
    { value: 101, rel:0, name: "İordaniya" },
    { value: 102, rel:0, name: "İraq" },
    { value: 103, rel:0, name: "İran İslam Respublikası" },
    { value: 104, rel:0, name: "İrlandiya" },
    { value: 105, rel:0, name: "İslandiya" },
    { value: 106, rel:0, name: "İspaniya" },
    { value: 107, rel:0, name: "İsrail" },
    { value: 108, rel:0, name: "İsveç" },
    { value: 109, rel:0, name: "İsveçrə" },
    { value: 111, rel:0, name: "İtaliya" },
    { value: 113, rel:0, name: "Kamboca" },
    { value: 114, rel:0, name: "Kamerun" },
    { value: 115, rel:0, name: "Kanada" },
    { value: 117, rel:0, name: "Keniya" },
    { value: 119, rel:0, name: "Kipr" },
    { value: 121, rel:0, name: "Kolumbiya" },
    { value: 122, rel:0, name: "Konqo" },
    { value: 123, rel:0, name: "Koreya (KXDR)" },
    { value: 124, rel:0, name: "Koreya Respublikası" },
    { value: 125, rel:0, name: "Kosta-Rika" },
    { value: 126, rel:0, name: "Kot-divuar" },
    { value: 127, rel:0, name: "Kuba" },
    { value: 130, rel:0, name: "Küveyt" },
    { value: 131, rel:0, name: "Laos (LXDR)" },
    { value: 132, rel:0, name: "Latviya" },
    { value: 133, rel:0, name: "Lesoto" },
    { value: 134, rel:0, name: "Liberiya" },
    { value: 135, rel:0, name: "Litva" },
    { value: 136, rel:0, name: "Livan" },
    { value: 137, rel:0, name: "Liviya" },
    { value: 138, rel:0, name: "Lixtenşteyn" },
    { value: 139, rel:0, name: "Lüksemburq" },
    { value: 140, rel:0, name: "Macarıstan" },
    { value: 141, rel:0, name: "Madaqaskar" },
    { value: 143, rel:0, name: "Makedoniya" },
    { value: 144, rel:0, name: "Malavi" },
    { value: 145, rel:0, name: "Malayziya" },
    { value: 146, rel:0, name: "Maldiv adaları" },
    { value: 147, rel:0, name: "Mali" },
    { value: 148, rel:0, name: "Malta" },
    { value: 149, rel:0, name: "Marşal adaları" },
    { value: 151, rel:0, name: "Mavrikiya" },
    { value: 152, rel:0, name: "Mavritaniya" },
    { value: 153, rel:0, name: "Meksika" },
    { value: 156, rel:0, name: "Mərakeş" },
    { value: 157, rel:0, name: "Mərkəzi Afrika Respublikası" },
    { value: 158, rel:0, name: "Mikroneziya Federativ Ştatları" },
    { value: 160, rel:0, name: "Misir" },
    { value: 162, rel:0, name: "Monqolustan" },
    { value: 163, rel:0, name: "Monteneqro" },
    { value: 165, rel:0, name: "Mozambik" },
    { value: 166, rel:0, name: "Müqəddəs Yelena Adası" },
    { value: 167, rel:0, name: "Myanma" },
    { value: 168, rel:0, name: "Namibiya" },
    { value: 169, rel:0, name: "Nauru" },
    { value: 170, rel:0, name: "Nepal" },
    { value: 171, rel:0, name: "Hollandiya" },
    { value: 173, rel:0, name: "Niger" },
    { value: 174, rel:0, name: "Nigeriya" },
    { value: 175, rel:0, name: "Nikaraqua" },
    { value: 178, rel:0, name: "Norveç" },
    { value: 179, rel:0, name: "Oman" },
    { value: 180, rel:0, name: "Qabon" },
    { value: 181, rel:0, name: "Qambiya" },
    { value: 182, rel:0, name: "Qana" },
    { value: 183, rel:0, name: "Qayana" },
    { value: 184, rel:0, name: "Qətər" },
    { value: 186, rel:0, name: "Qrenada" },
    { value: 190, rel:0, name: "Qvatemala" },
    { value: 191, rel:0, name: "Qvineya" },
    { value: 193, rel:0, name: "Özbəkistan" },
    { value: 194, rel:0, name: "Pakistan" },
    { value: 195, rel:0, name: "Palau" },
    { value: 197, rel:0, name: "Panama" },
    { value: 198, rel:0, name: "Papua-Yeni Qvineya" },
    { value: 199, rel:0, name: "Paraqvay" },
    { value: 200, rel:0, name: "Peru" },
    { value: 203, rel:0, name: "Polşa" },
    { value: 204, rel:0, name: "Portuqaliya" },
    { value: 205, rel:0, name: "Puerto-Riko (ABŞ)" },
    { value: 209, rel:0, name: "Ruanda" },
    { value: 210, rel:0, name: "Rumıniya" },
    { value: 212, rel:0, name: "Samoa" },
    { value: 213, rel:0, name: "San-Marino" },
    { value: 215, rel:0, name: "Seneqal" },
    { value: 222, rel:0, name: "Serbiya" },
    { value: 223, rel:0, name: "Seyşel adaları" },
    { value: 224, rel:0, name: "Səudiyyə Ərəbistanı" },
    { value: 225, rel:0, name: "Sinqapur" },
    { value: 227, rel:0, name: "Slovakiya" },
    { value: 228, rel:0, name: "Sloveniya" },
    { value: 230, rel:0, name: "Somali" },
    { value: 231, rel:0, name: "Sudan" },
    { value: 233, rel:0, name: "Surinam" },
    { value: 234, rel:0, name: "Suriya Ərəb Respublikası" },
    { value: 235, rel:0, name: "Svazilend" },
    { value: 236, rel:0, name: "Syerra-Leone" },
    { value: 239, rel:0, name: "Şri-Lanka" },
    { value: 240, rel:0, name: "Tailand" },
    { value: 241, rel:0, name: "Tayvan" },
    { value: 244, rel:0, name: "Tonqa" },
    { value: 245, rel:0, name: "Toqo" },
    { value: 246, rel:0, name: "Trinidad və Tobaqo" },
    { value: 247, rel:0, name: "Tunis" },
    { value: 249, rel:0, name: "Tuvalu" },
    { value: 250, rel:0, name: "Türkiyə" },
    { value: 251, rel:0, name: "Türkmənistan" },
    { value: 252, rel:0, name: "Uqanda" },
    { value: 253, rel:0, name: "Uruqvay" },
    { value: 254, rel:0, name: "Vanuatu" },
    { value: 255, rel:0, name: "Vatikan" },
    { value: 256, rel:0, name: "Venesuela" },
    { value: 260, rel:0, name: "Vyetnam" },
    { value: 261, rel:0, name: "Xorvatiya" },
    { value: 262, rel:0, name: "Yamayka" },
    { value: 263, rel:0, name: "Yaponiya" },
    { value: 265, rel:0, name: "Yeni Zelandiya" },
    { value: 266, rel:0, name: "Yəmən" },
    { value: 7 , rel:0, name: "Yunanıstan" },
    { value: 4 , rel:0, name: "Zimbabve" },
    { value: 5 , rel:0, name: "Zambiya" },
]


export const countries_ru = [
    { value:27, rel:0, name: "Albaniya" },
    { value:36, rel:0, name: "Argentina" },
    { value:10, rel:0, name: "Almaniya" },
    { value:29, rel:0, name: "Amerika Birləşmiş Ştatları" },
    { value:30, rel:0, name: "Amerika Samoası" },
    { value:31, rel:0, name: "Andorra" },
    { value:34, rel:0, name: "Antarktika" },
    { value:35, rel:0, name: "Antiqua və Barbuda" },
    { value:11, rel:1, name: "Belarus" },
    { value:12, rel:1, name: "Moldova Respublikası" },
    { value:13, rel:1, name: "Gürcüstan" },
    { value:14, rel:1, name: "Qazaxıstan" },
    { value:15, rel:1, name: "Qırğızıstan" },
    { value:16, rel:1, name: "Rusiya Federasiyası" },
    { value:17, rel:1, name: "Tacikistan" },
    { value:19, rel:1, name: "Ukrayna" },
    { value:24, rel:0, name: "Əlcəzair" },
    { value:33, rel:0, name: "Anqola" },
    { value:37, rel:0, name: "Aruba" },
    { value:38, rel:0, name: "Avstraliya" },
    { value:39, rel:0, name: "Avstriya" },
    { value:40, rel:0, name: "Azərbaycan" },
    { value:41, rel:0, name: "Baham adaları" },
    { value:42, rel:0, name: "Banqladeş" },
    { value:43, rel:0, name: "Barbados" },
    { value:44, rel:0, name: "Belçika" },
    { value:45, rel:0, name: "Beliz" },
    { value:46, rel:0, name: "Benin" },
    { value:47, rel:0, name: "Bermud adaları" },
    { value:48, rel:0, name: "Bəhreyn" },
    { value:49, rel:0, name: "Birləşmiş Ərəb Əmirlikləri" },
    { value:50, rel:0, name: "Birləşmiş Tanzaniya Respublikası" },
    { value:51, rel:0, name: "Boliviya" },
    { value:52, rel:0, name: "Bolqarıstan" },
    { value:53, rel:0, name: "Boneyr, Sent-Estatius və Saba" },
    { value:54, rel:0, name: "Bosniya və Herseqovina" },
    { value:55, rel:0, name: "Botsvana" },
    { value:56, rel:0, name: "Böyük Britaniya" },
    { value:57, rel:0, name: "Braziliya" },
    { value:58, rel:0, name: "Bruney-Darüssalam" },
    { value:59, rel:0, name: "Burkina-Faso" },
    { value:60, rel:0, name: "Burundi" },
    { value:61, rel:0, name: "Butan" },
    { value:64, rel:0, name: "Cəbəllütariq" },
    { value:65, rel:0, name: "Cənubi Afrika Respublikası" },
    { value:66, rel:0, name: "Cənubi Sudan" },
    { value:67, rel:0, name: "Cibuti" },
    { value:69, rel:0, name: "Çad" },
    { value:70, rel:0, name: "Çexiya Respublikası" },
    { value:71, rel:0, name: "Çili" },
    { value:72, rel:0, name: "Çin" },
    { value:73, rel:0, name: "Danimarka" },
    { value:74, rel:0, name: "Dominika" },
    { value:75, rel:0, name: "Dominikan Respublikası" },
    { value:76, rel:0, name: "Ekvador" },
    { value:77, rel:0, name: "Ekvatorial Qvineya" },
    { value:78, rel:0, name: "Eritreya" },
    { value:81, rel:0, name: "Estoniya" },
    { value:82, rel:0, name: "Farer adaları" },
    { value:83, rel:0, name: "Fici" },
    { value:84, rel:0, name: "Filippin" },
    { value:85, rel:0, name: "Finlandiya" },
    { value:87, rel:0, name: "Fransa" },
    { value:92, rel:0, name: "Haiti" },
    { value:97, rel:0, name: "Hindistan" },
    { value:98, rel:0, name: "Honduras" },
    { value: 100, rel:0, name: "İndoneziya" },
    { value: 101, rel:0, name: "İordaniya" },
    { value: 102, rel:0, name: "İraq" },
    { value: 103, rel:0, name: "İran İslam Respublikası" },
    { value: 104, rel:0, name: "İrlandiya" },
    { value: 105, rel:0, name: "İslandiya" },
    { value: 106, rel:0, name: "İspaniya" },
    { value: 107, rel:0, name: "İsrail" },
    { value: 108, rel:0, name: "İsveç" },
    { value: 109, rel:0, name: "İsveçrə" },
    { value: 111, rel:0, name: "İtaliya" },
    { value: 113, rel:0, name: "Kamboca" },
    { value: 114, rel:0, name: "Kamerun" },
    { value: 115, rel:0, name: "Kanada" },
    { value: 117, rel:0, name: "Keniya" },
    { value: 119, rel:0, name: "Kipr" },
    { value: 121, rel:0, name: "Kolumbiya" },
    { value: 122, rel:0, name: "Konqo" },
    { value: 123, rel:0, name: "Koreya (KXDR)" },
    { value: 124, rel:0, name: "Koreya Respublikası" },
    { value: 125, rel:0, name: "Kosta-Rika" },
    { value: 126, rel:0, name: "Kot-divuar" },
    { value: 127, rel:0, name: "Kuba" },
    { value: 130, rel:0, name: "Küveyt" },
    { value: 131, rel:0, name: "Laos (LXDR)" },
    { value: 132, rel:0, name: "Latviya" },
    { value: 133, rel:0, name: "Lesoto" },
    { value: 134, rel:0, name: "Liberiya" },
    { value: 135, rel:0, name: "Litva" },
    { value: 136, rel:0, name: "Livan" },
    { value: 137, rel:0, name: "Liviya" },
    { value: 138, rel:0, name: "Lixtenşteyn" },
    { value: 139, rel:0, name: "Lüksemburq" },
    { value: 140, rel:0, name: "Macarıstan" },
    { value: 141, rel:0, name: "Madaqaskar" },
    { value: 143, rel:0, name: "Makedoniya" },
    { value: 144, rel:0, name: "Malavi" },
    { value: 145, rel:0, name: "Malayziya" },
    { value: 146, rel:0, name: "Maldiv adaları" },
    { value: 147, rel:0, name: "Mali" },
    { value: 148, rel:0, name: "Malta" },
    { value: 149, rel:0, name: "Marşal adaları" },
    { value: 151, rel:0, name: "Mavrikiya" },
    { value: 152, rel:0, name: "Mavritaniya" },
    { value: 153, rel:0, name: "Meksika" },
    { value: 156, rel:0, name: "Mərakeş" },
    { value: 157, rel:0, name: "Mərkəzi Afrika Respublikası" },
    { value: 158, rel:0, name: "Mikroneziya Federativ Ştatları" },
    { value: 160, rel:0, name: "Misir" },
    { value: 162, rel:0, name: "Monqolustan" },
    { value: 163, rel:0, name: "Monteneqro" },
    { value: 165, rel:0, name: "Mozambik" },
    { value: 166, rel:0, name: "Müqəddəs Yelena Adası" },
    { value: 167, rel:0, name: "Myanma" },
    { value: 168, rel:0, name: "Namibiya" },
    { value: 169, rel:0, name: "Nauru" },
    { value: 170, rel:0, name: "Nepal" },
    { value: 171, rel:0, name: "Hollandiya" },
    { value: 173, rel:0, name: "Niger" },
    { value: 174, rel:0, name: "Nigeriya" },
    { value: 175, rel:0, name: "Nikaraqua" },
    { value: 178, rel:0, name: "Norveç" },
    { value: 179, rel:0, name: "Oman" },
    { value: 180, rel:0, name: "Qabon" },
    { value: 181, rel:0, name: "Qambiya" },
    { value: 182, rel:0, name: "Qana" },
    { value: 183, rel:0, name: "Qayana" },
    { value: 184, rel:0, name: "Qətər" },
    { value: 186, rel:0, name: "Qrenada" },
    { value: 190, rel:0, name: "Qvatemala" },
    { value: 191, rel:0, name: "Qvineya" },
    { value: 193, rel:0, name: "Özbəkistan" },
    { value: 194, rel:0, name: "Pakistan" },
    { value: 195, rel:0, name: "Palau" },
    { value: 197, rel:0, name: "Panama" },
    { value: 198, rel:0, name: "Papua-Yeni Qvineya" },
    { value: 199, rel:0, name: "Paraqvay" },
    { value: 200, rel:0, name: "Peru" },
    { value: 203, rel:0, name: "Polşa" },
    { value: 204, rel:0, name: "Portuqaliya" },
    { value: 205, rel:0, name: "Puerto-Riko (ABŞ)" },
    { value: 209, rel:0, name: "Ruanda" },
    { value: 210, rel:0, name: "Rumıniya" },
    { value: 212, rel:0, name: "Samoa" },
    { value: 213, rel:0, name: "San-Marino" },
    { value: 215, rel:0, name: "Seneqal" },
    { value: 222, rel:0, name: "Serbiya" },
    { value: 223, rel:0, name: "Seyşel adaları" },
    { value: 224, rel:0, name: "Səudiyyə Ərəbistanı" },
    { value: 225, rel:0, name: "Sinqapur" },
    { value: 227, rel:0, name: "Slovakiya" },
    { value: 228, rel:0, name: "Sloveniya" },
    { value: 230, rel:0, name: "Somali" },
    { value: 231, rel:0, name: "Sudan" },
    { value: 233, rel:0, name: "Surinam" },
    { value: 234, rel:0, name: "Suriya Ərəb Respublikası" },
    { value: 235, rel:0, name: "Svazilend" },
    { value: 236, rel:0, name: "Syerra-Leone" },
    { value: 239, rel:0, name: "Şri-Lanka" },
    { value: 240, rel:0, name: "Tailand" },
    { value: 241, rel:0, name: "Tayvan" },
    { value: 244, rel:0, name: "Tonqa" },
    { value: 245, rel:0, name: "Toqo" },
    { value: 246, rel:0, name: "Trinidad və Tobaqo" },
    { value: 247, rel:0, name: "Tunis" },
    { value: 249, rel:0, name: "Tuvalu" },
    { value: 250, rel:0, name: "Türkiyə" },
    { value: 251, rel:0, name: "Türkmənistan" },
    { value: 252, rel:0, name: "Uqanda" },
    { value: 253, rel:0, name: "Uruqvay" },
    { value: 254, rel:0, name: "Vanuatu" },
    { value: 255, rel:0, name: "Vatikan" },
    { value: 256, rel:0, name: "Venesuela" },
    { value: 260, rel:0, name: "Vyetnam" },
    { value: 261, rel:0, name: "Xorvatiya" },
    { value: 262, rel:0, name: "Yamayka" },
    { value: 263, rel:0, name: "Yaponiya" },
    { value: 265, rel:0, name: "Yeni Zelandiya" },
    { value: 266, rel:0, name: "Yəmən" },
    { value: 7 , rel:0, name: "Yunanıstan" },
    { value: 4 , rel:0, name: "Zimbabve" },
    { value: 5 , rel:0, name: "Zambiya" },
]